[Service]
ExecStart=
ExecStart=/bin/sh -c 'if [ -x /usr/libexec/bluetooth/bluetoothd ]; then exec /usr/libexec/bluetooth/bluetoothd -P battery; else exec /usr/lib/bluetooth/bluetoothd -P battery; fi'
