name: Build Debian Package

on:
  push:
    branches: [master]
    tags: ["debian/*"]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    uses: cix-oss/.github/.github/workflows/debian-package-build.yml@master
    with:
      artifact-name: ubuntu-cix-settings-debs
